[package]
name = "googler"
version = "0.1.0"
edition = "2021"

[dependencies]
serpapi-search-rust="0.1.0"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"